name: Build and Push Agent Image

on:
  pull_request:
  push:
    branches:
      - main
      - feat/github-actions-example

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install BeeAI CLI
        run: pip install -U "git+https://github.com/i-am-bee/beeai-platform.git@switch-to-a2a-protocol#subdirectory=apps/beeai-cli"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: '{"features": {"containerd-snapshotter": true}}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        run: |
          beeai build ./ --tag ghcr.io/${{ github.repository }}/my-agent-a2a:latest --no-import --multi-platform
          docker push ghcr.io/${{ github.repository }}/my-agent-a2a:latest